export const ACTIONS = {
  JOIN: 'join',
  LEAVE: 'leave',
  SHARE_ROOMS: 'share-rooms',
  GET_ROOMS: 'get-rooms',
  ADD_PEER: 'add-peer',
  REMOVE_PEER: 'remove-peer',
  RELAY_SDP: 'relay-sdp',
  RELAY_ICE: 'relay-ice',
  ICE_CANDIDATE: 'ice-candidate',
  SESSION_DESCRIPTION: 'session-description',
  DISCONNECT: 'disconnect',
  CONNECT: 'connect',
  CONNECTING: 'connecting',
  CONNECTION: 'connection',
  CONNECT_ERROR: 'connect_error',
  DISCONNECTING: 'disconnecting',
};
